name: limp-external-cbc
version: 0.1.0.0
github: "kfigiela/limp-external-cbc"
license: BSD3
author: "Kamil Figiela <kamil.figiela@gmail.com>"
maintainer: "Kamil Figiela <kamil.figiela@gmail.com>"
copyright: "2020 Kamil Figiela"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/kfigiela/limp-external-cbc#readme>

dependencies:
  - base >= 4.7 && < 5
  - limp
  - universum
  - fmt
  - text
  - containers
  - temporary
  - process
  - parsec
  - parsec-numbers
  - scientific

library:
  source-dirs: src

executables:
  limp-external-cbc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - limp-external-cbc

tests:
  limp-external-cbc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - limp-external-cbc
      - hspec
      - hspec-discover
      - hspec-expectations

default-extensions:
  - ConstraintKinds
  - DefaultSignatures
  - FlexibleContexts
  - FlexibleInstances
  - OverloadedStrings
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - UndecidableInstances
